// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0zNQK9i1Qaqi4ynaGJjt8MkRgEAnD6H0',
    appId: '1:744362264358:web:4101b2bcc0aa25955023e7',
    messagingSenderId: '744362264358',
    projectId: 'syncraft-69b84',
    authDomain: 'syncraft-69b84.firebaseapp.com',
    storageBucket: 'syncraft-69b84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7zHMB-7wZskHtN3eXFwdTqQPUdNRFtZQ',
    appId: '1:744362264358:android:87ac12ceea20000f5023e7',
    messagingSenderId: '744362264358',
    projectId: 'syncraft-69b84',
    storageBucket: 'syncraft-69b84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdlcTPBjd1b0CzDXA-MpnZriZkNHPcPY',
    appId: '1:744362264358:ios:b4719357481626385023e7',
    messagingSenderId: '744362264358',
    projectId: 'syncraft-69b84',
    storageBucket: 'syncraft-69b84.firebasestorage.app',
    iosBundleId: 'com.example.syncraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdlcTPBjd1b0CzDXA-MpnZriZkNHPcPY',
    appId: '1:744362264358:ios:b4719357481626385023e7',
    messagingSenderId: '744362264358',
    projectId: 'syncraft-69b84',
    storageBucket: 'syncraft-69b84.firebasestorage.app',
    iosBundleId: 'com.example.syncraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0zNQK9i1Qaqi4ynaGJjt8MkRgEAnD6H0',
    appId: '1:744362264358:web:e56bed69ae526e345023e7',
    messagingSenderId: '744362264358',
    projectId: 'syncraft-69b84',
    authDomain: 'syncraft-69b84.firebaseapp.com',
    storageBucket: 'syncraft-69b84.firebasestorage.app',
  );
}
